image: registry.cs.uni-bonn.de:5005/lehretool/cppreferencecontainer:main

stages:
  - test_compile

aufgabe_01:
  stage: test_compile
  script: 
    - cd uebungscode_05
    - clang++ -std=c++17 -I./include src/minsort_in_place.cpp examples/aufg1.cpp -o build/aufg1


aufgabe_02:
  stage: test_compile
  script: 
    - cd uebungscode_05
    - clang++ -std=c++17 -I./include src/hanoi.cpp examples/aufg2.cpp -o build/aufg2


aufgabe_03:
  stage: test_compile
  script: 
    - cd uebungscode_05
    - clang++ -std=c++17 -I./include src/hanoi.cpp src/hanoi_loesen.cpp examples/aufg3.cpp -o build/aufg3
